// Full 2026 Church Social Media & Ministry Content Calendar
// Each entry: week number, date range, key date, scripture theme, post ideas, sermon shots tip

export const calendar2026 = [
  // JANUARY
  { week: 1,  month: "January",  dates: "Jan 1–4",    keyDate: "New Year's Day",               scripture: "Jeremiah 29:11",         theme: "New Beginnings",         postIdeas: ["Share your church's vision for 2026", "Post a New Year's prayer for the congregation", "Ask: What is God calling you to this year?"], sermonShot: "Create a quote graphic with Jer 29:11 over a sunrise background. Use bold white text." },
  { week: 2,  month: "January",  dates: "Jan 5–11",   keyDate: "Epiphany (Jan 6)",              scripture: "Matthew 2:1-12",         theme: "Following the Light",    postIdeas: ["Share the story of the Wise Men", "Post: 'What star are you following this year?'", "Devotional clip on seeking Jesus"], sermonShot: "Use a dark starry background with a single bright star. Overlay Matt 2:2 in gold text." },
  { week: 3,  month: "January",  dates: "Jan 12–18",  keyDate: "Martin Luther King Jr. Week",   scripture: "Micah 6:8",              theme: "Justice & Unity",        postIdeas: ["Honor Dr. King's legacy with a quote post", "Share your church's community outreach", "Post: 'How is your church walking justly?'"], sermonShot: "Black and white photo background with MLK quote. Add your church logo in corner." },
  { week: 4,  month: "January",  dates: "Jan 19–25",  keyDate: "MLK Day (Jan 19)",              scripture: "Galatians 3:28",         theme: "One in Christ",          postIdeas: ["Unity Sunday announcement", "Highlight a diverse ministry moment", "Scripture graphic on equality"], sermonShot: "Colorful mosaic or hands-together image. Overlay Gal 3:28 in clean sans-serif font." },
  { week: 5,  month: "January",  dates: "Jan 26–Feb 1", keyDate: "End of January",             scripture: "Psalm 46:10",            theme: "Be Still",               postIdeas: ["Mid-week stillness devotional", "Prayer challenge post", "Behind-the-scenes of prayer team"], sermonShot: "Calm water or forest image. Minimal text: 'Be still and know.' Add church name subtly." },

  // FEBRUARY
  { week: 6,  month: "February", dates: "Feb 2–8",    keyDate: "Black History Month Begins",    scripture: "Acts 17:26",             theme: "Every Nation",           postIdeas: ["Celebrate Black History Month", "Spotlight a church member's story", "Post on God's diverse family"], sermonShot: "Vibrant Afrocentric pattern background. Bold scripture overlay. Share as a story or reel." },
  { week: 7,  month: "February", dates: "Feb 9–15",   keyDate: "Valentine's Day (Feb 14)",      scripture: "1 Corinthians 13:4-7",   theme: "Love",                   postIdeas: ["Marriage/couples appreciation post", "Post: 'God's definition of love'", "Couples prayer challenge"], sermonShot: "Soft pink/red background with heart motif. Use 1 Cor 13:4 as a pull quote graphic." },
  { week: 8,  month: "February", dates: "Feb 16–22",  keyDate: "Presidents' Day (Feb 16)",      scripture: "Romans 13:1",            theme: "Leadership & Service",   postIdeas: ["Prayer for leaders post", "Highlight servant leaders in your church", "Devotional on godly leadership"], sermonShot: "American flag or government building subtly blurred. Overlay Romans 13:1 in navy text." },
  { week: 9,  month: "February", dates: "Feb 23–Mar 1", keyDate: "End of Black History Month", scripture: "Revelation 7:9",         theme: "Great Multitude",        postIdeas: ["Celebrate diversity in the body of Christ", "Share a testimony from a church member", "Post a unity prayer"], sermonShot: "Crowd worship image. Overlay Rev 7:9 — 'every nation, tribe, people and language.'" },

  // MARCH
  { week: 10, month: "March",    dates: "Mar 2–8",    keyDate: "Ash Wednesday (Mar 4)",         scripture: "Joel 2:12-13",           theme: "Return to God",          postIdeas: ["Lent begins — post a 40-day devotional plan", "Ash Wednesday service announcement", "Post: 'What are you giving up for Lent?'"], sermonShot: "Dark moody background with ash cross image. Minimal text. Very powerful as a reel cover." },
  { week: 11, month: "March",    dates: "Mar 9–15",   keyDate: "Lent Week 1",                   scripture: "Matthew 4:1-11",         theme: "Temptation & Triumph",   postIdeas: ["Jesus in the wilderness devotional", "Fasting tips for Lent", "Daily scripture challenge post"], sermonShot: "Desert landscape image. Bold Matt 4:4 quote: 'Man shall not live on bread alone.'" },
  { week: 12, month: "March",    dates: "Mar 16–22",  keyDate: "Lent Week 2 / St. Patrick's Day (Mar 17)", scripture: "John 3:16", theme: "God So Loved",           postIdeas: ["St. Patrick's Day faith post", "John 3:16 graphic series", "Share the gospel simply"], sermonShot: "Green shamrock with cross overlay. Fun and shareable. Great for reaching new audiences." },
  { week: 13, month: "March",    dates: "Mar 23–29",  keyDate: "Lent Week 3",                   scripture: "Psalm 51:10",            theme: "Renewal",                postIdeas: ["Mid-Lent reflection post", "Confession and renewal devotional", "Ask: How is Lent changing you?"], sermonShot: "Watercolor wash background in purple (Lent color). Psalm 51:10 in elegant script font." },
  { week: 14, month: "March",    dates: "Mar 30–Apr 5", keyDate: "Palm Sunday (Apr 5)",         scripture: "Matthew 21:9",           theme: "Hosanna",                postIdeas: ["Palm Sunday service announcement", "Post: 'Who do you say Jesus is?'", "Share a palm branch photo from service"], sermonShot: "Palm branches photo with 'Hosanna!' overlay. Bright and celebratory. Great for stories." },

  // APRIL
  { week: 15, month: "April",    dates: "Apr 6–12",   keyDate: "Holy Week / Good Friday (Apr 10)", scripture: "Isaiah 53:5",         theme: "He Was Wounded for Us",  postIdeas: ["Good Friday service post", "Daily Holy Week scripture series", "Post: 'What the cross means to me'"], sermonShot: "Dark cross silhouette at sunset. Isaiah 53:5 in white. Powerful and shareable." },
  { week: 16, month: "April",    dates: "Apr 13–19",  keyDate: "Easter Sunday (Apr 13)",        scripture: "Luke 24:6",              theme: "He Is Risen",            postIdeas: ["Easter Sunday announcement", "Post: 'He is Risen — He is Risen Indeed!'", "Share Easter service highlights"], sermonShot: "Empty tomb or sunrise image. Bold 'HE IS RISEN' text. Your most shareable post of the year." },
  { week: 17, month: "April",    dates: "Apr 20–26",  keyDate: "Post-Easter Week",              scripture: "John 20:21",             theme: "Sent",                   postIdeas: ["Post-Easter mission focus", "Share how your church is going into the world", "New member/baptism announcement"], sermonShot: "Bright outdoor photo of congregation. Overlay John 20:21 — 'As the Father sent me...'" },
  { week: 18, month: "April",    dates: "Apr 27–May 3", keyDate: "End of April",               scripture: "Proverbs 3:5-6",         theme: "Trust the Lord",         postIdeas: ["Monthly reflection post", "Testimony Tuesday feature", "Post a trust challenge for the week"], sermonShot: "Road or path image looking forward. Proverbs 3:5 in clean bold font. Great for reels." },

  // MAY
  { week: 19, month: "May",      dates: "May 4–10",   keyDate: "Mother's Day Week",             scripture: "Proverbs 31:25",         theme: "Honoring Mothers",       postIdeas: ["Mother's Day service announcement", "Post: 'Tag a mom who inspires you'", "Share a mother's testimony"], sermonShot: "Floral background with Prov 31:25. Warm and elegant. Perfect for stories and feed posts." },
  { week: 20, month: "May",      dates: "May 11–17",  keyDate: "Mother's Day (May 10)",         scripture: "Psalm 127:3",            theme: "Children Are a Gift",    postIdeas: ["Family ministry spotlight", "Post a prayer for mothers", "Children's ministry highlight reel"], sermonShot: "Mother and child photo (stock or congregation). Psalm 127:3 overlay in soft script." },
  { week: 21, month: "May",      dates: "May 18–24",  keyDate: "Ascension Day (May 21)",        scripture: "Acts 1:8",               theme: "You Will Be My Witnesses", postIdeas: ["Ascension Day devotional", "Post: 'Where is your Jerusalem?'", "Missions update or spotlight"], sermonShot: "Sky/clouds image. Acts 1:8 in bold. Add a subtle upward arrow graphic element." },
  { week: 22, month: "May",      dates: "May 25–31",  keyDate: "Pentecost (May 31) / Memorial Day (May 25)", scripture: "Acts 2:1-4", theme: "Fire of the Spirit",    postIdeas: ["Pentecost Sunday announcement", "Memorial Day prayer for veterans", "Post: 'Come Holy Spirit'"], sermonShot: "Flame or fire image in red/orange. Acts 2:4 overlay. Red is the Pentecost color — use it!" },

  // JUNE
  { week: 23, month: "June",     dates: "Jun 1–7",    keyDate: "Pride Month / Men's Ministry",  scripture: "1 Corinthians 16:13",    theme: "Stand Firm in Faith",    postIdeas: ["Men's ministry spotlight", "Father's Day prep post", "Post a challenge for men of faith"], sermonShot: "Strong outdoor/nature image. 1 Cor 16:13 in bold masculine font. Great for men's ministry." },
  { week: 24, month: "June",     dates: "Jun 8–14",   keyDate: "Flag Day (Jun 14)",             scripture: "2 Chronicles 7:14",      theme: "Heal Our Land",          postIdeas: ["Prayer for the nation post", "Flag Day patriotic faith post", "Community prayer event announcement"], sermonShot: "American flag subtly blurred. 2 Chron 7:14 overlay. Timely and shareable." },
  { week: 25, month: "June",     dates: "Jun 15–21",  keyDate: "Father's Day (Jun 21)",         scripture: "Psalm 103:13",           theme: "Like a Father",          postIdeas: ["Father's Day service announcement", "Post: 'Tag a dad who leads with faith'", "Devotional on God as Father"], sermonShot: "Father and child silhouette at sunset. Psalm 103:13 in warm tones. Very shareable." },
  { week: 26, month: "June",     dates: "Jun 22–28",  keyDate: "Summer Begins",                 scripture: "Ecclesiastes 3:1",       theme: "A Season for Everything", postIdeas: ["Summer ministry schedule announcement", "VBS announcement", "Post: 'How are you growing this summer?'"], sermonShot: "Bright summer outdoor photo. Eccl 3:1 in playful font. Announce summer programs here." },

  // JULY
  { week: 27, month: "July",     dates: "Jun 29–Jul 5", keyDate: "Independence Day (Jul 4)",   scripture: "John 8:36",              theme: "True Freedom",           postIdeas: ["4th of July freedom in Christ post", "Post: 'Whom the Son sets free is free indeed'", "Prayer for the nation"], sermonShot: "Fireworks or flag image. John 8:36 in red/white/blue. Fun and patriotic faith content." },
  { week: 28, month: "July",     dates: "Jul 6–12",   keyDate: "Summer Ministry",               scripture: "Matthew 28:19",          theme: "Go and Make Disciples",  postIdeas: ["Mission trip update or announcement", "VBS highlight reel", "Post: 'Who are you discipling?'"], sermonShot: "Group mission photo or VBS kids. Matt 28:19 overlay. Authentic photos perform best here." },
  { week: 29, month: "July",     dates: "Jul 13–19",  keyDate: "Mid-Summer",                    scripture: "Isaiah 40:31",           theme: "Renewed Strength",       postIdeas: ["Mid-year encouragement post", "Post a summer scripture challenge", "Share a mid-year testimony"], sermonShot: "Eagle soaring image. Isaiah 40:31 in bold. One of the most shareable scriptures — use it!" },
  { week: 30, month: "July",     dates: "Jul 20–26",  keyDate: "Summer Outreach",               scripture: "Luke 10:2",              theme: "The Harvest Is Plentiful", postIdeas: ["Community outreach event post", "Volunteer spotlight", "Post: 'How is your church reaching the community?'"], sermonShot: "Harvest field or community service photo. Luke 10:2 overlay. Recruit volunteers here." },
  { week: 31, month: "July",     dates: "Jul 27–Aug 2", keyDate: "End of July",                scripture: "Philippians 4:13",       theme: "I Can Do All Things",    postIdeas: ["Monthly encouragement post", "Back-to-school prep announcement", "Post a strength challenge"], sermonShot: "Athletic or determined person image. Phil 4:13 in bold. Extremely shareable — great reach." },

  // AUGUST
  { week: 32, month: "August",   dates: "Aug 3–9",    keyDate: "Back to School Season",         scripture: "Proverbs 22:6",          theme: "Train Up a Child",       postIdeas: ["Back to school prayer post", "Children's/youth ministry announcement", "Post: 'Praying for students this year'"], sermonShot: "School supplies or backpack image. Prov 22:6 in bright colors. Tag parents and teachers." },
  { week: 33, month: "August",   dates: "Aug 10–16",  keyDate: "Back to School",                scripture: "Joshua 1:9",             theme: "Be Strong and Courageous", postIdeas: ["Encouragement post for students", "Teacher appreciation post", "Post a back-to-school blessing"], sermonShot: "Student walking into school. Josh 1:9 overlay. Powerful for parents to share." },
  { week: 34, month: "August",   dates: "Aug 17–23",  keyDate: "Late Summer",                   scripture: "Colossians 3:23",        theme: "Work as for the Lord",   postIdeas: ["Labor Day prep post", "Highlight church volunteers", "Post: 'Whatever you do, do it for God'"], sermonShot: "Hands working or serving image. Col 3:23 in clean font. Great for volunteer recruitment." },
  { week: 35, month: "August",   dates: "Aug 24–30",  keyDate: "End of Summer",                 scripture: "Lamentations 3:22-23",   theme: "New Every Morning",      postIdeas: ["Fall season preview post", "Monthly gratitude post", "Share what God did this summer"], sermonShot: "Sunrise image. Lam 3:22-23 in soft morning tones. Reflective and widely shareable." },

  // SEPTEMBER
  { week: 36, month: "September", dates: "Aug 31–Sep 6", keyDate: "Labor Day (Sep 7)",         scripture: "Colossians 3:17",        theme: "Do It All for God",      postIdeas: ["Labor Day rest and worship post", "Highlight church staff/volunteers", "Post: 'Your work is worship'"], sermonShot: "Peaceful rest or nature image. Col 3:17 overlay. Simple and reflective." },
  { week: 37, month: "September", dates: "Sep 7–13",  keyDate: "Fall Kickoff Season",           scripture: "Psalm 100:4",            theme: "Enter with Thanksgiving", postIdeas: ["Fall ministry kickoff announcement", "New sermon series launch post", "Post: 'What are you thankful for this fall?'"], sermonShot: "Fall leaves or warm tones. Psalm 100:4 in rich autumn colors. Announce fall series here." },
  { week: 38, month: "September", dates: "Sep 14–20", keyDate: "Hispanic Heritage Month Begins", scripture: "Romans 10:12",          theme: "No Difference",          postIdeas: ["Hispanic Heritage Month celebration post", "Spotlight a Hispanic ministry leader", "Post on the global church"], sermonShot: "Vibrant cultural imagery. Romans 10:12 overlay. Celebrate diversity in your congregation." },
  { week: 39, month: "September", dates: "Sep 21–27", keyDate: "Fall Equinox (Sep 22)",         scripture: "Psalm 19:1",             theme: "Creation Declares",      postIdeas: ["Creation and nature devotional", "Post a beautiful fall photo from your area", "Ask: Where do you see God in creation?"], sermonShot: "Stunning fall landscape. Psalm 19:1 in minimal text. Let the image do the talking." },

  // OCTOBER
  { week: 40, month: "October",  dates: "Sep 28–Oct 4", keyDate: "World Communion Sunday (Oct 5)", scripture: "1 Corinthians 11:26", theme: "Proclaim His Death",     postIdeas: ["Communion Sunday announcement", "Post on the meaning of the Lord's Supper", "Global church unity post"], sermonShot: "Bread and cup image. 1 Cor 11:26 in reverent font. Powerful for communion Sundays." },
  { week: 41, month: "October",  dates: "Oct 5–11",   keyDate: "Breast Cancer Awareness Month",  scripture: "Psalm 34:18",            theme: "Near to the Brokenhearted", postIdeas: ["Prayer post for those facing illness", "Highlight a healing testimony", "Post: 'God is near to the brokenhearted'"], sermonShot: "Pink ribbon or soft light image. Psalm 34:18 in gentle font. Compassionate and shareable." },
  { week: 42, month: "October",  dates: "Oct 12–18",  keyDate: "Mid-October",                   scripture: "2 Timothy 1:7",          theme: "Spirit of Power",        postIdeas: ["Spiritual warfare devotional", "Post: 'God has not given us a spirit of fear'", "Prayer for boldness challenge"], sermonShot: "Bold warrior or armor image. 2 Tim 1:7 in strong font. Great for men's and youth ministry." },
  { week: 43, month: "October",  dates: "Oct 19–25",  keyDate: "Reformation Day (Oct 31)",       scripture: "Romans 1:17",            theme: "The Just Shall Live by Faith", postIdeas: ["Reformation Day history post", "Post on grace and faith", "Share your church's doctrinal foundation"], sermonShot: "Old church door or parchment texture. Romans 1:17 in classic serif font. Educational content." },
  { week: 44, month: "October",  dates: "Oct 26–Nov 1", keyDate: "Halloween / All Saints Day",  scripture: "Ephesians 6:12",         theme: "Spiritual Warfare",      postIdeas: ["All Saints Day post honoring those who passed", "Post: 'We don't fight flesh and blood'", "Light vs. darkness devotional"], sermonShot: "Light breaking through darkness image. Eph 6:12 overlay. Contrast makes this very striking." },

  // NOVEMBER
  { week: 45, month: "November", dates: "Nov 2–8",    keyDate: "Election Season",               scripture: "1 Timothy 2:1-2",        theme: "Pray for Leaders",       postIdeas: ["Prayer for election/leaders post", "Post: 'Pray for those in authority'", "Encourage civic engagement with faith"], sermonShot: "Ballot box or Capitol building blurred. 1 Tim 2:1-2 overlay. Nonpartisan and powerful." },
  { week: 46, month: "November", dates: "Nov 9–15",   keyDate: "Veterans Day (Nov 11)",          scripture: "John 15:13",             theme: "Greater Love",           postIdeas: ["Veterans Day honor post", "Prayer for military families", "Post: 'Greater love has no one than this'"], sermonShot: "Military silhouette or flag image. John 15:13 in bold. Honor veterans with this graphic." },
  { week: 47, month: "November", dates: "Nov 16–22",  keyDate: "Thanksgiving Week Prep",         scripture: "1 Thessalonians 5:18",   theme: "Give Thanks",            postIdeas: ["Thanksgiving countdown posts", "Post: '30 days of gratitude' challenge", "Highlight church blessings this year"], sermonShot: "Warm autumn table or harvest image. 1 Thess 5:18 in cozy script font. Very shareable." },
  { week: 48, month: "November", dates: "Nov 23–29",  keyDate: "Thanksgiving (Nov 26)",          scripture: "Psalm 107:1",            theme: "Give Thanks to the Lord", postIdeas: ["Thanksgiving service announcement", "Post: 'What are you most thankful for?'", "Share a year-in-review gratitude post"], sermonShot: "Family around table or hands folded in prayer. Psalm 107:1 overlay. Warm and inviting." },

  // DECEMBER
  { week: 49, month: "December", dates: "Nov 30–Dec 6", keyDate: "Advent Begins (Nov 30)",      scripture: "Isaiah 9:6",             theme: "Wonderful Counselor",    postIdeas: ["Advent Week 1 — Hope post", "Advent candle lighting announcement", "Post: 'The names of Jesus' series"], sermonShot: "Advent wreath with one candle lit. Isaiah 9:6 in elegant gold font. Start your Advent series." },
  { week: 50, month: "December", dates: "Dec 7–13",   keyDate: "Advent Week 2",                 scripture: "Luke 1:37",              theme: "Nothing Is Impossible",  postIdeas: ["Advent Week 2 — Peace post", "Share a miracle testimony", "Post: 'What impossible thing are you trusting God for?'"], sermonShot: "Two Advent candles lit. Luke 1:37 in soft white on dark background. Peaceful and reverent." },
  { week: 51, month: "December", dates: "Dec 14–20",  keyDate: "Advent Week 3 / Christmas Events", scripture: "Luke 2:10-11",        theme: "Good News of Great Joy",  postIdeas: ["Christmas Eve/Day service announcement", "Advent Week 3 — Joy post", "Post: 'Share the good news this Christmas'"], sermonShot: "Three candles lit. Luke 2:10-11 in joyful bright font. Promote Christmas services here." },
  { week: 52, month: "December", dates: "Dec 21–31",  keyDate: "Christmas (Dec 25) / New Year's Eve", scripture: "John 1:14",       theme: "The Word Became Flesh",  postIdeas: ["Christmas Day post", "New Year's Eve reflection post", "Post: 'Year in review — God's faithfulness'", "Preview 2027 vision"], sermonShot: "Nativity scene or candlelight. John 1:14 in gold. End the year with your most beautiful graphic." },
];

export const sermonShotsIntro = {
  title: "Bonus: How to Use Sermon Shots",
  description: "Sermon Shots is a tool that helps churches create stunning visuals from sermon clips, scripture quotes, and devotionals — without needing a designer.",
  tips: [
    { icon: "🎬", title: "Sermon Clips", tip: "Record a 60-second clip from your sermon, upload to Sermon Shots, and it auto-generates captions and branded graphics ready for Instagram Reels and Facebook." },
    { icon: "📖", title: "Scripture Quote Images", tip: "Paste any scripture from this calendar into Sermon Shots. Choose a background template, pick your church colors, and download a shareable image in seconds." },
    { icon: "🙏", title: "Devotional Graphics", tip: "Turn your weekly post ideas into devotional image series. Use the same template each week for brand consistency — your congregation will start recognizing your style." },
    { icon: "📱", title: "Stories & Reels", tip: "Every week's Sermon Shot tip is optimized for vertical format (9:16). Use the suggested background and text placement for maximum engagement on Stories." },
    { icon: "🎨", title: "Brand Consistency", tip: "Set your church colors and logo once in Sermon Shots. Every graphic you create will automatically match your brand — no design skills needed." },
    { icon: "📅", title: "Batch Create", tip: "Spend one hour per month creating all your graphics for the next 4 weeks using this calendar. Schedule them in advance with Buffer or Meta Business Suite." },
  ],
};
